[package]
name = "routeros-proto"
version = "0.1.0"
authors = ["Alex Gavrisco <alexandr@gavrisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[features]
default = ["alloc"]
alloc = []
