on:
  push:
    branches: ["main"]

name: Publish docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Rust
        run: rustup update stable
      - name: Build docs
        run: "cargo doc --workspace --no-deps --all-features"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: "target/doc/"
          target-folder: "docs/"
